server:
  port: 80


spring:
  application:
    name: cloud-order-service  # 服务注册名


eureka:
  client:
    register-with-eureka: true #我们是服务端需要向注册服务中心注册自己
    fetch-registry: true #true抓取已有的注册信息，默认为true，单点无所谓，集群必须为true才能配合ribbon使用
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http:/eureka7002.com:7002/eureka #集群版