server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册服务中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    service-url:
      # 集群执行爱过你其他Eureka
      # defaultZone: http://eureka7002.com:7002/eureka/
      #单机就就7001自己
      defaultZone: http://eureka7001.com:7001/eureka/
    #server:
      # 关闭自我保护机制，保证不可以攻服务被及时踢掉
      # enable-self-preservation: false
      # eviction-interval-timer-ms: 2000
